
name: Build  Image
on:
  push:
    branches: [ main ]

env:
  BASE_REPO: disco-diffusion-aiges-demo 

jobs:
  build-prep-image:
    runs-on: ubuntu-latest
    # 项目构建
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.IFLYOPENSOURCE }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build Docker Image -cuda-base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/prep/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.IFLYOPENSOURCE }}/${{env.BASE_REPO}}:prep
  build-main-image:
    needs: build-prep-image
    runs-on: ubuntu-latest
    # 项目构建
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.IFLYOPENSOURCE }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build Docker Image -cuda-base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/main/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.IFLYOPENSOURCE }}/${{env.BASE_REPO}}:main

